version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: ibuni-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ibuni
      - POSTGRES_USER=ibuniuser
      - POSTGRES_PASSWORD=ibunipass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
